(ns prob-02)

(comment
  "Problem 2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


"
)

(defn lazy-seq-fibo
    ([]
        (concat [0 1] (lazy-seq-fibo 0 1)))
    ([a b]
        (let [n (+ a b)]
            (lazy-seq
                (cons n (lazy-seq-fibo b n))))))

(defn less-than-four-million? [n]
  (< n 4000000))

(defn calculation []
  (reduce + (filter even? (take-while less-than-four-million? (lazy-seq-fibo)))))

;;=> (calculation)
;;4613732